import Head from 'next/head'
import About from '../components/About'
import BackToTopBtn from '../components/BackToTopBtn'
import Brands from '../components/Brands'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Portfolio from '../components/Portfolio'
import Services from '../components/Services'
import Skills from '../components/Skills'
// import Testimonials from '../components/Testimonials'
import { client } from '../lib/client'

export default function Home({
  courses,
  HeroData,
  BrandData,

  AboutData,
}) {
  console.log(courses, HeroData, BrandData, AboutData)
  return (
    <div>
      <Head>
        <title>Loctech | Training | Leaning</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div>
          <Header />
          <Hero HeroData={HeroData.length && HeroData[0]} />
          <Brands BrandData={BrandData} />
          <About AboutData={AboutData} />
          <Skills />
          <Portfolio />
          <Services />
          {/* <Testimonials /> */}
          <Contact />
          <Footer />
          <BackToTopBtn />
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const query = '*[_type == "course"]'
  const courses = await client.fetch(query)

  const HeroQuery = '*[_type == "hero"]'
  const HeroData = await client.fetch(HeroQuery)

  const BrandQuery = '*[_type == "brand"]'
  const BrandData = await client.fetch(BrandQuery)

  const AboutQuery = '*[_type == "about"]'
  const AboutData = await client.fetch(AboutQuery)

  return {
    props: {
      courses,
      HeroData,
      BrandData,
      AboutData,
    },
  }
}
